Started on new test for m_new_outbound_msg

diff --git a/tst/muse/bin/mu_test_muse_common_funcs b/tst/muse/bin/mu_test_muse_common_funcs
--- a/tst/muse/bin/mu_test_muse_common_funcs
+++ b/tst/muse/bin/mu_test_muse_common_funcs
@@ -197,7 +197,7 @@ end
 #======================================
 def Test-m_check_file
     #======================================
-    # Requires
+    # Requires and Imports / Exports
     #======================================
     require_file m_fail_raise_error
     require_file m_fail_record_failure
@@ -248,7 +248,7 @@ end
 #======================================
 def Test-m_get_usr_tag
     #======================================
-    # Requires
+    # Requires and Imports / Exports
     #======================================
     require_file common.funcs
     require_file m_fail_record_failure
@@ -309,7 +309,7 @@ end
 #======================================
 def Test-m_get_exp_file
     #======================================
-    # Requires
+    # Requires and Imports / Exports
     #======================================
     require_file common.funcs
     require_file m_fail_record_failure
@@ -359,7 +359,7 @@ end
 #======================================
 def Test-m_get_unique_tmp_file
     #======================================
-    # Requires
+    # Requires and Imports / Exports
     #======================================
     require_file common.funcs
     require_file m_fail_record_failure
@@ -413,7 +413,7 @@ end
 #======================================
 def Test-m_get_tmp_file
     #======================================
-    # Requires
+    # Requires and Imports / Exports
     #======================================
     require_file common.funcs
     require_file m_fail_record_failure
@@ -468,7 +468,7 @@ end
 #======================================
 def Test-m_get_tmp_dir
     #======================================
-    # Requires
+    # Requires and Imports / Exports
     #======================================
     require_file common.funcs
     require_file m_fail_record_failure
@@ -517,3 +517,123 @@ def Test-m_get_tmp_dir
 
     [[ -f "${MU_TMP}/common.funcs" ]] && rm -f "${MU_TMP}/common.funcs"
 end
+
+def Test-m_clean_file
+    #======================================
+    # Requires and Imports / Exports
+    #======================================
+    require_file common.funcs
+    require_file m_clean_file.src
+    require_file m_fail_record_failure
+    require_file m_fail_raise_error
+    import m_fail_raise_error
+    import common.funcs
+
+    export M_TMP="${MU_TMP}"
+    
+    #======================================
+    # Run the positive tests
+    #======================================
+    ## Write new clean version of src file
+    mu_find_file m_clean_file.src SRC
+    mu_get_exp_file m_clean_file CLF
+    m_clean_file "${SRC}" "${CLF}"
+    mu_find_file m_clean_file.exp EXP
+    assert_is_not_different "${EXP}" "${CLF}"
+
+    ## Overwrite SRC file with clean version
+    TSRC="${MU_TMP}/Test-m_clean_file.src"
+    cp "${SRC}" "${TSRC}" || raise_error "Failed to copy src file (${SRC}) to dst dir (${TSRC})"
+    m_clean_file "${TSRC}" "${TSRC}"
+    assert_is_not_different "${EXP}" "${TSRC}"
+
+    #======================================
+    # Negative tests
+    #======================================
+    mu_find_file common.funcs FUT
+    sed 's/\(m_fail .*\)/\1 || return 1/g' "${FUT}" > "${MU_TMP}/common.funcs"
+    import common.funcs
+    import m_fail_record_failure
+
+    ## Rig test version of m_fail
+    mu_get_exp_file Test-m_clean_file FAIL
+    export M_FAIL="${FAIL}"
+
+    #======================================
+    # Src abd dst same file
+    #======================================
+    ## Arg count
+    cp "${SRC}" "${TSRC}" || raise_error "Failed to copy src file (${SRC}) to dst dir (${TSRC})"
+    m_clean_file "${TSRC}" && raise_failure "Failed to trap incorrect arg count"
+    ## Fail file perms check read
+    chmod -r "${TSRC}"
+    m_clean_file "${TSRC}" "${TSRC}" 2>/dev/null && raise_failure "Failed to trap perms invalid"
+    ## Fail file perms check write
+    chmod +r "${TSRC}"
+    chmod -w "${TSRC}"
+    m_clean_file "${TSRC}" "${TSRC}" 2>/dev/null && raise_failure "Failed to trap perms invalid"
+
+    #======================================
+    # Src and dst different
+    #======================================
+    ## Fail file perms check read
+    TMP="${MU_TMP}/Test-m_clean_file.tmp"
+    cp "${SRC}" "${TMP}" || raise_error "Failed to copy src file (${SRC}) to dst dir (${TSRC})"
+    chmod -r "${TSRC}"
+    chmod +w "${TMP}"
+    m_clean_file "${TSRC}" "${TMP}" 2>/dev/null && raise_failure "Failed to trap perms invalid"
+    ## Fail file perms check write
+    chmod +r "${TSRC}"
+    chmod -w "${TMP}"
+    m_clean_file "${TSRC}" "${TMP}" 2>/dev/null && raise_failure "Failed to trap perms invalid"
+
+    #======================================
+    # Confirm we have all the correct error 
+    # msgs
+    #======================================
+    mu_find_file m_clean_file_2.exp EXP2
+    assert_is_not_different "${EXP2}" "${FAIL}"
+end
+
+#======================================
+# Function writes a message to the msgs
+# table in the master db and also a msg
+# file to the outbound msg dir.
+#======================================
+def Test-m_new_outbound_msg
+
+    #======================================
+    # Requires and Imports / Exports
+    #======================================
+    require_file common.funcs
+    require_file comm.funcs
+    require_file db.funcs
+    require_file master.db
+    require_file m_fail_record_failure
+    require_file m_fail_raise_error
+    import m_fail_raise_error
+    import common.funcs
+    import comm.funcs
+    import db.funcs
+
+    export M_TMP="${MU_TMP}"
+
+    #======================================
+    # Get a copy of the master db
+    #======================================
+    mu_find_file master.db MUDB
+    cp "${MUDB}" "${MU_TMP}"
+    mu_find_file sqlite3 SQL3
+    export M_DB_FILE="${MU_TMP}/master.db"
+    export M_DB="${SQL3} ${M_DB_FILE}"
+    export M_DB_RETRY=50
+    
+    #======================================
+    # Run the positive tests
+    #======================================
+    m_new_outbound_msg "1" "123456789" "1" "2" "server.src" "server.dst" "TEST" "PL" "OUTBOUND" "NEW" "8441bbc0b0573b183bc62dee5966fdc1" MSG_ID
+
+
+end
+
+
